name: ghibloo_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dash_chat_2: ^0.0.20
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.3
  get: ^4.6.6
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/onboarding/
    - assets/images/
